### PR TITLE
Move scigraph util to ontobio; better handling of ontobio objects; set owlsim limits

### PR DESCRIPTION
**Pull request by kshefchek**
This is the companion PR for https://github.com/biolink/ontobio/pull/588

- [x] Move scigraph_util and biomodel data style classes to ontobio
- [x] #380
- [ ] ~~Remove biolink yaml configuration and set ontobios config via a .env file~~
- [ ] ~~Improve how we're creating ontobio objects to fix some of my hacky singleton work~~

Going to come back to 3 and 4 in another PR

### CODE REVIEW

**Comment by kshefchek** [comment]
note that the tests will fail until biolink/ontobio#588 is merged and put on pypi

**Review by sierra-moxon — APPROVED** [review]

**Comment by kshefchek** [comment]
@dustine32 would it be possible to push a new release of ontobio? I'll need it to get these tests to pass

**Comment by dustine32** [comment]
@kshefchek Oh yes, for sure I will make an `ontobio` release today!

**Comment by dustine32** [comment]
@kshefchek Just released `ontobio-2.7.11`!

**Pull request merged**
