### PR TITLE
Get metadata for datasets

### PR DESCRIPTION
**Pull request by deepakunni3**
Add route to fetch metadata for datasets from SciGraph.

Currently the metadata is minimal. 
Will depend on future ingest for a more detailed metadata.

@kshefchek @cmungall

Related to https://github.com/monarch-initiative/monarch-ui/issues/58

### CODE REVIEW

**Review by cmungall — APPROVED** [review]
nice, looks like we already had the dynamic route in scigraph

(I think calling these Ontologies is confusing though)

**Comment by deepakunni3** [comment]
The dynamic route was added to SciGraph by @kshefchek 
Yes, calling it ontologies is confusing but it reflects a bigger problem that all datasets (and ontologies) are referred as type Ontology in SciGraph.

We can refine this further in the future once we fix this in SG.

**Comment by kshefchek** [comment]
I think this is a scigraph-ism, to have things annotated with isDefinedBy (edge properties) and edges to "ontology" nodes, we type our data file IRIs as an owl:Ontology.  I wonder how difficult it would be to make this more flexible - for example this work for dc:datasets

**Review by kshefchek — APPROVED** [review]

**Comment by pnrobinson** [comment]
Goal -- information analogous to this: http://amigo.geneontology.org/amigo/load_details

**Pull request merged**
