### PR TITLE
Configuration of endpoints in BioLink (closed)

### PR DESCRIPTION
**Pull request by deepakunni3**
Added the ability to initialize routes as dictated by `config.yaml`.
Currently the config.yaml includes all routes (by default). 

The idea is to have an implementation specific config.yaml (for example GO BioLink API specific config.yaml) that defines which routes to initialize.

@cmungall @lpalbou Related to #235. Let me know what you think.

If this approach seems feasible then I can start breaking `biolink.api.bio.endpoints.bioentity` into resource specific chunks. This way it would be easy to mix and match different parts of the API and show only the relevant routes.

### CODE REVIEW

**Comment by deepakunni3** [comment]
How `config.yaml` would look like:

```yaml
solr_assocs:
  url: "https://solr.monarchinitiative.org/solr/golr"
  timeout: 5
amigo_solr_assocs:
  url: "http://golr.berkeleybop.org"
  timeout: 4
solr_search:
  url: "https://solr.monarchinitiative.org/solr/search"
  timeout: 2
amigo_solr_search:
  url: "http://golr.berkeleybop.org"
  timeout: 2
sparql:
  url: "http://sparql.hegroup.org/sparql"
  timeout: 2
scigraph_ontology:
  url: "https://scigraph-ontology.monarchinitiative.org/scigraph/"
  timeout: 2
scigraph_data:
  url: "https://scigraph-data.monarchinitiative.org/scigraph/"
  timeout: 2
use_amigo_for:
  - function
ontologies:
  - id: go
    handle: go
    pre_load: true
  - id: hp
    handle: hp
    pre_load: true
  - id: mp
    handle: mp
    pre_load: true
  - id: uberon
    handle: uberon
    pre_load: true
  - id: monarch
    handle: data/monarch.json
    pre_load: true
biolink_modules:
  - 'biolink.api.bio.endpoints.bioentity'
  - 'biolink.api.link.endpoints.associations_from'
  - 'biolink.api.link.endpoints.find_associations'
  - 'biolink.api.search.endpoints.entitysearch'
  - 'biolink.api.ontol.endpoints.ontology_endpoint'
  - 'biolink.api.ontol.endpoints.subgraph'
  - 'biolink.api.ontol.endpoints.termstats'
  - 'biolink.api.ontol.endpoints.labeler'
  - 'biolink.api.ontol.endpoints.enrichment'
  - 'biolink.api.entityset.endpoints.summary'
  - 'biolink.api.entityset.endpoints.slimmer'
  - 'biolink.api.entityset.endpoints.geneset_homologs'
  - 'biolink.api.entityset.endpoints.overrepresentation'
  - 'biolink.api.nlp.endpoints.annotate'
  - 'biolink.api.graph.endpoints.node'
  - 'biolink.api.ontol.endpoints.subgraph'
  - 'biolink.api.mart.endpoints.mart'
  - 'biolink.api.cam.endpoints.cam_endpoint'
  - 'biolink.api.owl.endpoints.ontology'
  - 'biolink.api.patient.endpoints.individual'
  - 'biolink.api.identifier.endpoints.prefixes'
  - 'biolink.api.identifier.endpoints.mapper'
  - 'biolink.api.genome.endpoints.region'
  - 'biolink.api.pair.endpoints.pairsim'
  - 'biolink.api.evidence.endpoints.graph'
  - 'biolink.api.relations.endpoints.relation_usage'
  - 'biolink.api.variation.endpoints.variantset'
  - 'biolink.api.pub.endpoints.pubs'
```

**Review by cmungall — APPROVED** [review]
Love it!

**Comment by deepakunni3** [comment]
@cmungall Did you happen to take a look at #237 ? Just wanted to make sure which approach would be more flexible in the long run.

**Comment by deepakunni3** [comment]
Closing this PR in favor of https://github.com/biolink/biolink-api/pull/237

**Pull request closed without merging**
