### PR TITLE
Add scigraph annotator routes

### PR DESCRIPTION
**Pull request by deepakunni3**
This PR implements two new routes:
- `api/annotate`, which calls `scigraph/annotations` 
- `api/annotate/entities`, which calls `scigraph/annotations/entities`

Both GET and POST are implemented for these routes.

See https://github.com/biolink/biolink-api/issues/223 for related discussion.

### CODE REVIEW

**Comment by deepakunni3** [comment]
@kshefchek  Fixed the Behave tests but Travis is failing because `biolink-api:master` now relies on `ontobio:master` instead of a stable release of Ontobio, which is what `requirements.txt` specifies.

**Comment by kshefchek** [comment]
Maybe we should have travis test the master version of ontobio?  Is there a reason to have biolink coupled to an older version of ontobio?

**Comment by deepakunni3** [comment]
Ontobio is actively being developed as part of Gene Ontology and Monarch.
Locking the requirements.txt was to avoid any issues that might be introduced with new changes to Ontobio.

Are you suggesting we just have two requirements.txt,
- one for prod (ontobio:stable-release)
- one for dev (ontobio:master)

**Comment by kshefchek** [comment]
@deepakunni3 whatever you think is best.  I develop biolink against the master branch of ontobio, and in Monarch we test both master versions of ontobio and biolink on api-dev, and then update production when this is stable.

**Review by kshefchek — APPROVED** [review]

**Comment by kshefchek** [comment]
I've bumped the ontobio version if you'd like to pull from master and see if the tests pass

**Comment by kshefchek** [comment]
there are still 4 behave tests failing, but let's merge and fix these in the next PR

**Comment by monicacecilia** [comment]
Does this address and close #223 now? Or do we need to wait for the updated PR?

**Comment by kshefchek** [comment]
partially -- we'll need to update the UI to use biolink instead of scigraph

**Pull request merged**
