### PR TITLE
over-representation/enrichment first pass

### PR DESCRIPTION
**Pull request by cmungall**

### CODE REVIEW

**Comment by nathandunn** [comment]
I don't know if it works, but we can definitely wrap these and make them available in the galaxy toolshed.  I'm happy to push / test, but I don't know how to do that.   I would probably just extend biolink monarch: https://github.com/nathandunn/biolink-monarch  to incorporate the changes if that is where this data will be hosted.

**Comment by nathandunn** [comment]
Let me know when its available and I will give it a shot.

**Comment by cmungall** [comment]
This creates a new route `bioentityset/overrepresentation/`, e.g. http://localhost:5000/api/bioentityset/overrepresentation/?object_category=phenotype&object_category=phenotype&ontology=hp&subject=NCBIGene%3A9342&subject=NCBIGene%3A7227&subject=NCBIGene%3A8131&subject=NCBIGene%3A157570&subject=NCBIGene%3A51164&subject=NCBIGene%3A6689&subject=NCBIGene%3A6387&taxon=NCBITaxon%3A9606

It can be deployed at any time. Some improvements required:

 - [ ] better API swagger docs / example
 - [ ] make it possible to configure an endpoint to start up with certain ontologies pre-loaded
 - [ ] create a config specifically for the DC demo
 - [ ] perform resolution of symbols (currently you need to pass IDs)
 - [ ] wrap the GO one so that genes can be used as well/instead of proteins

**Comment by cmungall** [comment]
Should be on https://api-dev.monarchinitiative.org/api/ shortly

https://api-dev.monarchinitiative.org/api/bioentityset/overrepresentation/?object_category=phenotype&subject=NCBIGene%3A6295&subject=NCBIGene%3A1258&subject=NCBIGene%3A3614&subject=NCBIGene%3A26121&subject=NCBIGene%3A7275&subject=NCBIGene%3A55857&subject=NCBIGene%3A79797&subject=NCBIGene%3A10594&subject=NCBIGene%3A64218&subject=NCBIGene%3A7401&ontology=hp&subject_category=gene&taxon=NCBITaxon%3A9606&object_category=phenotype&max_p_value=0.05

**Pull request merged**
