### PR TITLE
Add facet_fields parameter to all Bioentity routes

### PR DESCRIPTION
**Pull request by deepakunni3**
@kshefchek This PR basically adds `facet_fields` parameter to all Bioentity routes.

And when `facet_fields` is `None`, the default `subject_taxon_label` and `object_closure` is used.
This is to ensure that we don't break any existing implementations that might assume that these fields are faceted. But this default behavior may be removed in a future release.

This PR is related to https://github.com/monarch-initiative/monarch-ui/issues/168

### CODE REVIEW

**Comment by deepakunni3** [comment]
Travis failing due to api.mi.org being down

**Comment by kshefchek** [comment]
I reran the travis tests now that all of our services are stable, but same results.  Odd, I had similar logs on my recent PR

**Review by kshefchek — APPROVED** [review]

**Comment by deepakunni3** [comment]
@kshefchek It looks like a lot of the behave tests are failing, mostly due to change in the data.
Routes that yielded results before now return empty.

Ex: `/api/bioentity/publication/PMID:20220848/genotypes` should return an association with object being `MONARCH:FBgeno426941`, but now there are no associations.

Is this expected?

**Comment by kshefchek** [comment]
This is expected, we removed fly genotypes in this release

**Comment by deepakunni3** [comment]
@kshefchek Thanks for merging the PR.

I'll fix the behave tests in a separate PR. I made some assumptions regarding the data which is likely to change from one release to another.

**Pull request merged**
