### PR TITLE
create an endpoint for getting gene to variant associations

### PR DESCRIPTION
**Pull request by deepakunni3**
PR for #154 

@nathandunn I added an endpoint that allows to get variants associated with a given gene.

Let me know if you need some additional information that needs to be fetched from Monarch Solr along with the variants.

### CODE REVIEW

**Comment by nathandunn** [comment]
@deepakunni3  If you have a sample JSON that would be great.   Otherwise I'm sure its fine to go in as is and change if needed.

**Comment by deepakunni3** [comment]
@nathandunn Here is a Gist with the response JSON: https://gist.github.com/deepakunni3/57a8eec4ff08c3fb9a7828e90cc6a965

**Comment by nathandunn** [comment]
@deepakunni3  I think this looks good. 

The only thing I would add would be location information.   I remember not having it as part of dipper, so I would probably just merge it as-is.  

Thanks!

**Comment by deepakunni3** [comment]
@nathandunn Closing this PR in favor of https://github.com/biolink/biolink-api/pull/170 that includes the call `/bioentity/gene/{id}/variants/`, where the result is much more correct (gene is the subject and variant is the object in the associations returned) than what was done in this PR.

**Comment by nathandunn** [comment]
🥇

**Pull request closed without merging**
