### PR TITLE
Switch from 'categories' field to 'category' in model and serializers

### PR DESCRIPTION
**Pull request by deepakunni3**
@kshefchek

### CODE REVIEW

**Comment by kshefchek** [comment]
I thought I got all these over in https://github.com/biolink/biolink-api/pull/330#issuecomment-543967657 but I'll have to take a closer look

**Comment by kshefchek** [comment]
here is that commit - https://github.com/biolink/biolink-api/pull/330/commits/b2105e9161097bb40791e2c9439d8e0497c1e120

**Comment by deepakunni3** [comment]
Any chance we can get #330 merged in soon? 

If not, I would vote for this PR to be merged as I can get the latest change running off of api-dev

This is a dependency for a demo for STAGE that isn't working anymore because `category` ends up as null

**Comment by kshefchek** [comment]
is stage running off of api prod or dev?  api-dev is running off of #330 so perhaps I missed one

**Comment by deepakunni3** [comment]
Oh! I was not aware of that.

The demo was using prod until now. I switched to dev.
I'll close this PR since what I want is already in dev.

Confirmed by the following query: https://api-dev.monarchinitiative.org/api/bioentity/HP:0002099

**Pull request closed without merging**
